apiVersion: v1
kind: Service
metadata:
    name: ubuntu-service
    labels:
        app: kk
spec:
    selector:
        app: kk
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 22
    externalIPs:
        - 10.192.0.2
